apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  neuralbank.conf: |
    server {
        listen 8080;
        server_name _;
        
        # Logs para depuración
        access_log /dev/stdout;
        error_log /dev/stderr;

        # Headers estándar para Proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # ------------------------------------------------------------
        # 1. API Backend (/api)
        # ------------------------------------------------------------
        location /api/ {
            # Sin barra al final en proxy_pass para pasar el path completo
            proxy_pass http://{{ .Release.Name }}-backend-svc:8080;
        }

        # ------------------------------------------------------------
        # 2. Swagger UI (Backend)
        # ------------------------------------------------------------
        # Quarkus necesita ambos paths para que cargue la UI y los recursos
        location /swagger-ui {
             proxy_pass http://{{ .Release.Name }}-backend-svc:8080/swagger-ui;
        }
        
        # Recursos estáticos de Quarkus (JS, CSS del Swagger)
        location /q/ {
             proxy_pass http://{{ .Release.Name }}-backend-svc:8080/q/;
        }

        # ------------------------------------------------------------
        # 3. Frontend (Puerto 8080)
        # ------------------------------------------------------------
        location / {
            # CORRECCIÓN: Apuntamos al puerto 8080 del servicio frontend
            proxy_pass http://{{ .Release.Name }}-frontend-svc:8080;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: neuralbank-proxy
    app.openshift.io/runtime: nginx
  annotations:
    app.openshift.io/connects-to: "{{ .Release.Name }}-backend,{{ .Release.Name }}-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-proxy
  template:
    metadata:
      labels:
        app: neuralbank-proxy
    spec:
      serviceAccountName: neuralbank-proxy-sa
      containers:
        - name: nginx
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          ports:
            - name: http-web  
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 101 
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: neuralbank.conf
      volumes:
        - name: nginx-config
          configMap:
            name: proxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-svc
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    app: neuralbank-proxy
  ports:
    - name: http-proxy  
      protocol: TCP
      port: 80          
      targetPort: 8080  